import {useEffect,useState} from 'react';
import {MessageCircle,Send,Users,RefreshCw,Wallet,Coins,Bell,ArrowUpRight} from 'lucide-react';
import PageHeader from '../../components/layout/PageHeader';import Card from '../../components/common/Card';import {get,post} from '../../api/client';
export default function ChatPage(){
 const[messages,setMessages]=useState([]),[text,setText]=useState(''),[busy,setBusy]=useState(false),[target,setTarget]=useState(''),[currency,setCurrency]=useState('RUB'),[amount,setAmount]=useState(''),[notifications,setNotifications]=useState([]),[unread,setUnread]=useState(0);
 async function load(){try{const [chat,n] = await Promise.all([get('/api/social/chat'),get('/api/social/notifications')]);setMessages(chat);setNotifications(n);setUnread(n.filter(x=>!x.read).length)}catch{}}
 useEffect(()=>{load();const t=setInterval(load,2000);return()=>clearInterval(t)},[]);
 async function send(e){e.preventDefault();if(!text.trim())return;setBusy(true);try{await post('/api/social/chat',{text:text.trim()});setText('');await load()}catch(e){alert(e.message)}finally{setBusy(false)}}
 async function transfer(e){e.preventDefault();if(!target.trim()||Number(amount)<=0)return;try{await post('/api/social/transfer',{recipient:target.trim(),currency,amount:Number(amount)});setAmount('');setTarget('');alert('Перевод выполнен');load()}catch(e){alert(e.message)}}
 async function read(){try{await post('/api/social/notifications/read');load()}catch{}}
 return <><PageHeader title="FENIX CHAT" subtitle="Живой городской канал, переводы и уведомления в одном месте." action="Обновить" onAction={load}/>
 <div className="social-hub-grid">
  <Card className="chat-shell live-panel"><div className="chat-head"><div><span className="eyebrow">LIVE CITY CHAT · 2 SEC</span><h2><MessageCircle/> FENIX CITY</h2></div><span className="live-dot">● ONLINE</span></div><div className="chat-feed">{messages.length?messages.map(m=><div className={m.own?'chat-msg own':'chat-msg'} key={m.id}><div className="chat-avatar">{m.sender.slice(0,1).toUpperCase()}</div><div><b>{m.sender}</b><p>{m.text}</p><small>{new Date(m.created_at).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}</small></div></div>):<div className="empty-state"><MessageCircle size={32}/><b>Город пока молчит</b><span>Напиши первое сообщение.</span></div>}</div><form className="chat-compose" onSubmit={send}><input value={text} onChange={e=>setText(e.target.value)} placeholder="Напиши сообщение..." maxLength={1000}/><button disabled={busy}><Send size={18}/></button></form></Card>
  <div className="social-side">
   <Card className="transfer-card"><div className="section-title"><div><span className="eyebrow">PLAYER MARKET</span><h2><ArrowUpRight/> Перевод</h2></div><Wallet/></div><form className="stack-form" onSubmit={transfer}><input value={target} onChange={e=>setTarget(e.target.value)} placeholder="Ник игрока"/><div className="transfer-row"><select value={currency} onChange={e=>setCurrency(e.target.value)}><option value="RUB">₽ RUB</option><option value="FC">FC</option></select><input type="number" min="1" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Сумма"/></div><button><Wallet size={16}/> Отправить</button></form><p className="muted">Перевод проходит на сервере и сразу появляется у получателя.</p></Card>
   <Card className="notifications-card"><div className="section-title"><div><span className="eyebrow">NOTIFICATIONS</span><h2><Bell/> Уведомления {unread>0&&<span className="notification-count">{unread}</span>}</h2></div><button className="icon-button" onClick={read}><RefreshCw size={16}/></button></div><div className="notification-list">{notifications.slice(0,7).map(n=><div className={`notification ${n.read?'':'unread'}`} key={n.id}><div className="notification-icon">{n.kind==='money'?<Wallet size={15}/>:n.kind==='battle'?<Users size={15}/>:<Bell size={15}/>}</div><div><b>{n.title}</b><p>{n.text}</p><small>{new Date(n.created_at).toLocaleString('ru-RU')}</small></div></div>)}{!notifications.length&&<p className="muted">Новых событий нет.</p>}</div></Card>
  </div>
 </div>
 <div className="social-cards"><Card><Users/><b>Игроки</b><strong>LIVE</strong><p>Общайся, договаривайся и передавай ₽ или FC.</p></Card><Card><RefreshCw/><b>Автообновление</b><strong>2 сек</strong><p>Чат и уведомления обновляются без перезагрузки.</p></Card><Card><Coins/><b>Серверная экономика</b><strong>SAFE</strong><p>Баланс меняется только через API.</p></Card></div></>}
