import {useEffect,useState} from 'react';
import {Gauge,CarFront,Wind,Settings2,Zap,Shield,Palette,ChevronUp,CheckCircle2} from 'lucide-react';
import PageHeader from '../../components/layout/PageHeader';import Card from '../../components/common/Card';import {get,post} from '../../api/client';
const COLORS=['#ff6a00','#ff3d71','#7c5cff','#18c8ff','#53e36c','#e9edf3'];
function CarVisual({name,klass}){return <div className={`car-visual class-${String(klass).replace('+','plus').toLowerCase()}`}><div className="car-sky"/><div className="car-body"><div className="car-roof"/><div className="car-window"/><div className="car-light l"/><div className="car-light r"/><div className="wheel w1"/><div className="wheel w2"/></div><span>{name}</span></div>}
export default function GaragePage({player,refresh}){
 const[cars,setCars]=useState([]),[owned,setOwned]=useState([]),[busy,setBusy]=useState(false),[selected,setSelected]=useState(null);
 const load=async()=>{const [all,mine]=await Promise.all([get('/api/vehicles'),get(`/api/player/${player.id}/vehicles`)]);setCars(all);setOwned(mine);if(!selected&&mine[0])setSelected(mine[0])};useEffect(()=>{load()},[player.id]);
 async function buy(id){setBusy(true);try{await post(`/api/player/${player.id}/vehicle/${id}/buy`);await load();refresh()}catch(e){alert(e.message)}finally{setBusy(false)}}
 async function upgrade(kind){if(!selected)return;setBusy(true);try{await post(`/api/player/${player.id}/vehicle/${selected.id}/upgrade`,{kind});await load();refresh()}catch(e){alert(e.message)}finally{setBusy(false)}}
 async function selectCar(){if(!selected)return;try{await post(`/api/player/${player.id}/vehicle/${selected.id}/select`);refresh();alert('Основной автомобиль выбран')}catch(e){alert(e.message)}}
 return <><PageHeader title="ГАРАЖ" subtitle="Коллекция машин, состояние, прокачка и тюнинг."/>
 <div className="garage-hero"><div><span className="eyebrow">FENIX GARAGE</span><h2>{owned.length} / {cars.length} автомобилей</h2><p>Каждая машина имеет характеристики и собственную прокачку.</p></div><div className="garage-count"><CarFront size={30}/><b>{owned.length}</b></div></div>
 {selected&&<Card className="garage-tuning"><div className="tuning-main"><CarVisual name={selected.vehicle.name} klass={selected.vehicle.class}/><div className="tuning-info"><span className="badge">{selected.vehicle.class} CLASS · LVL {selected.level}</span><h2>{selected.vehicle.name}</h2><div className="tuning-stats"><span><Zap/> {selected.vehicle.power} л.с.</span><span><Gauge/> {selected.vehicle.speed} км/ч</span><span><Wind/> {selected.vehicle.handling} grip</span><span><Shield/> {selected.condition}%</span></div><div className="tuning-bar"><span style={{width:`${selected.condition}%`}}/></div><small>Состояние · {selected.condition}%</small></div></div><div className="tuning-actions"><button onClick={()=>upgrade('power')} disabled={busy}><Zap/> +МОЩНОСТЬ</button><button onClick={()=>upgrade('speed')} disabled={busy}><Gauge/> +СКОРОСТЬ</button><button onClick={()=>upgrade('handling')} disabled={busy}><Wind/> +УПРАВЛЕНИЕ</button><button onClick={()=>upgrade('repair')} disabled={busy}><Settings2/> РЕМОНТ</button><button className="ghost-orange" onClick={selectCar}><CheckCircle2/> СДЕЛАТЬ ОСНОВНОЙ</button></div></Card>}
 <div className="section"><div className="section-title"><h2>МОЯ КОЛЛЕКЦИЯ</h2></div><div className="cards vehicle-grid">{owned.map(x=><Card key={x.id} className={`vehicle-card ${selected?.id===x.id?'selected':''}`} onClick={()=>setSelected(x)}><CarVisual name={x.vehicle.name} klass={x.vehicle.class}/><div className="vehicle-card-info"><b>{x.vehicle.name}</b><span>LVL {x.level} · {x.condition}%</span></div></Card>)}</div></div>
 <div className="section"><div className="section-title"><h2>АВТОСАЛОН · 15 МОДЕЛЕЙ</h2><span>Покупай и собирай коллекцию</span></div><div className="cards vehicle-grid">{cars.map(x=><Card key={x.id} className="dealer-card"><CarVisual name={x.name} klass={x.class}/><div className="dealer-top"><span className="badge">CLASS {x.class}</span><span>{x.handling} grip</span></div><h2>{x.name}</h2><div className="car-stats"><span><Gauge size={15}/> {x.speed}</span><span>⚡ {x.power} л.с.</span><span>↪ {x.handling}</span></div><div className="price">{x.price.toLocaleString('ru-RU')} ₽</div>{x.owned?<div className="owned">Уже в гараже</div>:<button onClick={()=>buy(x.id)} disabled={busy}>Купить автомобиль</button>}</Card>)}</div></div></>
}
