import {useEffect,useState} from 'react';
import {Shield,Users,MessageSquare,Swords,Plus,Send,Crown,LogOut,Trophy,RefreshCw} from 'lucide-react';
import PageHeader from '../../components/layout/PageHeader';import Card from '../../components/common/Card';import {get,post} from '../../api/client';
export default function FamilyPage(){
 const[data,setData]=useState(null),[families,setFamilies]=useState([]),[battles,setBattles]=useState([]),[text,setText]=useState(''),[form,setForm]=useState({name:'',tag:'',description:''}),[busy,setBusy]=useState(false),[opponent,setOpponent]=useState('');
 async function load(){try{const [me,fs,bs]=await Promise.all([get('/api/families/me'),get('/api/families'),get('/api/families/battles')]);setData(me);setFamilies(fs);setBattles(bs)}catch{}}
 useEffect(()=>{load();const t=setInterval(load,4000);return()=>clearInterval(t)},[]);
 async function create(e){e.preventDefault();try{await post('/api/families',form);setForm({name:'',tag:'',description:''});load()}catch(e){alert(e.message)}}
 async function join(id){try{await post(`/api/families/${id}/join`);load()}catch(e){alert(e.message)}}
 async function leave(){if(!confirm('Выйти из семьи?'))return;try{await post(`/api/families/${data.family.id}/leave`);load()}catch(e){alert(e.message)}}
 async function role(pid,role){try{await post(`/api/families/${data.family.id}/members/${pid}/role`,{role});load()}catch(e){alert(e.message)}}
 async function createBattle(e){e.preventDefault();if(!opponent)return;try{await post(`/api/families/${data.family.id}/battles`,{opponent_family_id:Number(opponent)});setOpponent('');load()}catch(e){alert(e.message)}}
 async function score(id){try{await post(`/api/families/battles/${id}/score`,{points:10});load()}catch(e){alert(e.message)}}
 async function send(e){e.preventDefault();if(!data?.family||!text.trim())return;setBusy(true);try{await post(`/api/families/${data.family.id}/chat`,{text});setText('');load()}catch(e){alert(e.message)}finally{setBusy(false)}}
 return <><PageHeader title="СЕМЬИ" subtitle="Глава, роли, семейный чат, рейтинг и реальные PvP-битвы." action="Обновить" onAction={load}/><div className="family-grid">{data?.family?<>
  <Card className="family-hero"><div className="family-emblem"><Shield size={38}/></div><div className="family-hero-main"><span className="eyebrow">FENIX FAMILY · [{data.family.tag}]</span><h1>{data.family.name}</h1><p>Уровень {data.family.level} · Рейтинг {data.family.rating.toLocaleString('ru-RU')} · Казна {data.family.treasury.toLocaleString('ru-RU')} ₽</p></div><button className="ghost-orange family-leave" onClick={leave}><LogOut size={16}/> Выйти</button></Card>
  <Card><div className="section-title"><h2><Users/> Участники</h2><span>{data.family.members.length}</span></div>{data.family.members.map(x=><div className="row family-member-row" key={x.id}><span><b>{x.nickname}</b> <small>LVL {x.level} · REP {x.reputation}</small></span><span className="role-actions"><b className="family-role">{x.role}</b>{data.family.my_role==='leader'&&<></>}</span></div>)}</Card>
  <Card className="family-chat"><div className="section-title"><div><span className="eyebrow">PRIVATE FAMILY CHANNEL</span><h2><MessageSquare/> Семейный чат</h2></div><span>LIVE</span></div><FamilyMessages fid={data.family.id}/><form className="chat-compose" onSubmit={send}><input value={text} onChange={e=>setText(e.target.value)} placeholder="Сообщение семье..."/><button disabled={busy}><Send size={18}/></button></form></Card>
  <Card><div className="section-title"><div><span className="eyebrow">FAMILY WAR</span><h2><Swords/> Битвы семей</h2></div><RefreshCw size={17}/></div><p className="muted">Набирайте 100 очков совместными действиями. Каждое действие участника добавляет очки.</p>{battles.map(b=><div className="battle-row" key={b.id}><div><b>{b.a} <span>VS</span> {b.b}</b><small>{b.status==='active'?'Битва идёт':'Завершена'}</small></div><strong>{b.score_a} : {b.score_b}</strong>{b.status==='active'&&<button onClick={()=>score(b.id)}>+10 ⚔️</button>}</div>)}</Card>
  <Card><div className="section-title"><h2><Crown/> Управление</h2></div><p className="muted">Глава управляет составом. Роли: leader / officer / member.</p>{data.family.my_role==='leader' ? data.family.members.map(x=><div className="role-control" key={x.id}><span><b>{x.nickname}</b><small>{x.role}</small></span><div><button onClick={()=>role(x.id,'officer')}>Офицер</button><button onClick={()=>role(x.id,'member')}>Участник</button></div></div>) : <div className="muted">Управление составом доступно только главе семьи.</div>}</Card>
  <Card><div className="section-title"><h2>Начать битву</h2></div><form className="battle-form" onSubmit={createBattle}><select value={opponent} onChange={e=>setOpponent(e.target.value)}><option value="">Выбери соперника</option>{families.filter(f=>f.id!==data.family.id).map(f=><option key={f.id} value={f.id}>[{f.tag}] {f.name}</option>)}</select><button><Swords size={16}/> Вызвать</button></form></Card>
 </>:<><Card><h2>Создать семью</h2><form className="stack-form" onSubmit={create}><input placeholder="Название" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/><input placeholder="Тег 2–8 символов" value={form.tag} onChange={e=>setForm({...form,tag:e.target.value.toUpperCase()})} required/><input placeholder="Описание" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><button><Plus/> Создать семью</button></form></Card><Card><div className="section-title"><h2>Семьи города</h2><span>{families.length}</span></div>{families.map(f=><div className="family-list-row" key={f.id}><div className="family-mini"><span>[{f.tag}]</span><b>{f.name}</b><small>LVL {f.level} · {f.members} участников · {f.rating} рейтинга</small></div><button disabled={f.mine} onClick={()=>join(f.id)}>{f.mine?'Твоя семья':'Вступить'}</button></div>)}</Card></>}</div></>}
function FamilyMessages({fid}){const[m,setM]=useState([]);useEffect(()=>{let alive=true;const load=()=>get(`/api/families/${fid}/chat`).then(x=>alive&&setM(x)).catch(()=>{});load();const t=setInterval(load,2500);return()=>{alive=false;clearInterval(t)}},[fid]);return <div className="family-feed">{m.map(x=><div className={x.own?'chat-msg own':'chat-msg'} key={x.id}><div className="chat-avatar">{x.sender[0]}</div><div><b>{x.sender}</b><p>{x.text}</p><small>{new Date(x.created_at).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}</small></div></div>)}</div>}
