import {useEffect,useState} from 'react';
import {ShieldCheck,Users,Wallet,Coins,Zap,Plus,RefreshCw,Terminal} from 'lucide-react';
import PageHeader from '../../components/layout/PageHeader';
import Card from '../../components/common/Card';
import {get,post} from '../../api/client';
export default function AdminPage(){
 const [data,setData]=useState(null),[selected,setSelected]=useState(null),[busy,setBusy]=useState(false);
 const [cash,setCash]=useState(0),[coins,setCoins]=useState(0),[xp,setXp]=useState(0),[energy,setEnergy]=useState('');
 async function load(){try{setData(await get('/api/admin/overview'))}catch(e){setData({error:e.message})}}
 useEffect(()=>{load()},[]);
 async function grant(){if(!selected)return;setBusy(true);try{await post(`/api/admin/player/${selected.id}/grant`,{cash:Number(cash)||0,coins:Number(coins)||0,xp:Number(xp)||0,energy:energy===''?null:Number(energy)});setCash(0);setCoins(0);setXp(0);setEnergy('');await load()}catch(e){alert(e.message)}finally{setBusy(false)}}
 if(data?.error)return <Card><h2>DEV PANEL</h2><p className="error">{data.error}</p></Card>;
 return <><PageHeader title="DEV PANEL" subtitle="Серверное управление FENIX CITY" action="Обновить" onAction={load}/><div className="admin-hero"><div className="admin-glow"><ShieldCheck size={34}/></div><div><span className="eyebrow">DEVELOPER ACCESS</span><h2>FENIX / Developer</h2><p>Админ-панель работает через серверные права.</p></div></div><div className="market-summary admin-stats"><Card><Users/><span>Игроков</span><strong>{data?.counts.players||0}</strong></Card><Card><Wallet/><span>Транзакций</span><strong>{data?.counts.transactions||0}</strong></Card><Card><Terminal/><span>Автомобилей</span><strong>{data?.counts.vehicles||0}</strong></Card></div><div className="admin-grid"><Card><div className="section-title"><h2>Игроки</h2><RefreshCw size={17}/></div><div className="admin-players">{(data?.players||[]).map(p=><button key={p.id} className={selected?.id===p.id?'admin-player active':'admin-player'} onClick={()=>setSelected(p)}><span className="admin-avatar">{p.nickname.slice(0,1).toUpperCase()}</span><span><b>{p.nickname}</b><small>ID {p.id} · LVL {p.level}</small></span><strong>{p.cash.toLocaleString('ru-RU')} ₽</strong></button>)}</div></Card><Card><div className="section-title"><h2>Выдача ресурсов</h2><Plus size={17}/></div>{selected?<><div className="admin-target"><b>{selected.nickname}</b><span>ID {selected.id} · {selected.role}</span></div><label>₽<input className="admin-input" type="number" value={cash} onChange={e=>setCash(e.target.value)}/></label><label>FC<small>Добавить/забрать</small><input className="admin-input" type="number" value={coins} onChange={e=>setCoins(e.target.value)}/></label><label>XP<input className="admin-input" type="number" value={xp} onChange={e=>setXp(e.target.value)}/></label><label>Энергия 0–100<input className="admin-input" type="number" min="0" max="100" value={energy} onChange={e=>setEnergy(e.target.value)}/></label><button className="admin-grant" disabled={busy} onClick={grant}>{busy?'Применение…':'Применить изменения'}</button></>:<p className="muted">Выбери игрока слева.</p>}</Card></div></>
}
